version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "8080:80"  
    volumes:
      - ./paneladmin:/var/www/html  
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: ""  
    ports:
      - "3306:3306" 
    volumes:
      - /var/lib/mysql:/var/lib/mysql  

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    ports:
      - "8081:80"  
    environment:
      PMA_HOST: mysql  
      MYSQL_ALLOW_EMPTY_PASSWORD: ""  