version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    ports:
      - "8080:80"
    volumes:
      - ./paneladmin:/var/www/html
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: ${SA_PASSWORD} 
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"  
    ports:
      - "1433:1433"
    volumes:
      - 'C:/Program Files/Microsoft SQL Server:/var/opt/mssql'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    depends_on:
      - mssql
    environment:
      PMA_HOST: mssql
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
